### ISSUE TITLE
A bug

### ISSUE THREAD

**Issue by SkyLionel** [vijos/vj4#177]
![1](https://cloud.githubusercontent.com/assets/27768986/25531563/c9920b2c-2c5c-11e7-8fd0-d9fef3f44d3e.png)
If you have give the solution a good mark, and now it can't see.
And even you can give it two bad mark.

**Comment by twd2** [comment]
It may be at the top.

**Comment by breeswish** [comment]
Both by design.
- After giving a up-vote, the solution's rank will be higher so that it will appear at top.
- If you have already voted up previously, by clicking "vote down" 1 time you will revert previous voting (operation: vote -= 1) and by clicking twice you will give a down vote. Of course you can give up-vote again (vote += 1) to revert that down-vote.

**Comment by SkyLionel** [comment]
I don't mean it.and it is solved now
