### ISSUE TITLE
Can't log in in a domain which limit guest to access

### ISSUE THREAD

**Issue by ksyx** [vijos/vj4#234]

**Comment by twd2** [comment]
Known bug. Do you have a good solution?

**Comment by ksyx** [comment]
How about set a whitelist? Links in the whitelist can be accessed by any user.  
It's better to point out which link is in the whitelist in code. 
(We think it's in the whitelist if you can find the link in the URL, such as */login*, we think
*example.com/login* and *example.com/d/exampledomain/login* are in the whitelist because all these strings include */login*)

**Comment by breeswish** [comment]
Login is a site specific operation, not domain specific operation. Login URL should always be `/login`.

**Comment by ksyx** [comment]
@breeswish
Yes, it is. But login operation was excuted on *vijos.org/d/domain_name/login* and the domain can't be accessed when the permission "Visit this domain" for guests is not checked.

**Comment by breeswish** [comment]
@ksyx 
So if I understand correctly, when the login URL is "/login", this problem won't happen by natural?

**Comment by ksyx** [comment]
I think this bug was fixed... 
> twd2 referenced this issue from commit 6ac2cbb about 16 hours ago

**Comment by breeswish** [comment]
It changed the rule from:
> limit access according to the domain settings by the domain prefix
into:
> limit access according to the domain settings by the domain prefix, except for those URLs marked as a globalRoute (still contains the domain prefix)

It does not solve:
> Login is a site specific operation, not domain specific operation. Login URL should always be /login.

**Comment by twd2** [comment]
How can users come back to the desired domain after visit `/login`, ... ?

**Comment by breeswish** [comment]
user should not come back to the domain.instead user come back to the page he previously visited. i.e. return URL.

**Comment by ksyx** [comment]
How about add a parameter of return URL?(for example *vijos.org/login?returnto=vijos.org/p/1000*)

**Comment by breeswish** [comment]
Yes that's a typical solution.

**Comment by twd2** [comment]
/home is also a site specific page, so how can users come back to the desired domain after visit /home, ... ?

**Comment by breeswish** [comment]
@twd2 

The "returning domain" and "the privilege checking by domain" is not orthogonal, because sometimes we want to return to a domain in a system page, while the system page should not have a domain-scope privilege checking, just as you said. Mixing them together and solving them by using a "domain prefix" implementation is wrong, just because they can't be mixed together.

Now let's think about implement them independently. If "privilege checking by domain" uses "domain prefix", then "returning domain" can use something like, (1) extra query string, (2) hidden field indicating the current domain

**Comment by twd2** [comment]
???

**Comment by ksyx** [comment]
I think i met a fake @twd2 ...

**Comment by twd2** [comment]
???
